version: '3.7'
services:
  challenge-db:
    image: "mysql/mysql-server:5.7.25"
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=8VNHNkphA6hvkqDT
      - MYSQL_USER=hand6wecUHdR2jQA
      - MYSQL_PASSWORD=8VNHNkphA6hvkqDT
      - MYSQL_DATABASE=challenge_banks
    container_name: challenge-db

volumes:
  db-data: {}